"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['../main.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'packages': ['mlx_lm', 'objc', 'AppKit', 'ApplicationServices', 'Foundation'],
}

setup(
    app=APP,
    name='Zero',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
